openapi: 3.0.0
info:
  title: EnergyMe - Home | API
  description: API documentation for EnergyMe - Home
  version: 1.1.0

servers:
  - url: /
    description: Current server (auto-detected from browser)

paths:
  # Health check endpoint
  /api/v1/health:
    get:
      summary: Health check
      description: Check if the API is running and responsive
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  uptime:
                    type: integer
                    format: seconds
                  timestamp:
                    type: string
                    format: date-time

  # Authentication endpoints  
  /api/v1/auth/status:
    get:
      summary: Get authentication status
      description: Check if the current session is authenticated
      tags:
        - Authentication
      responses:
        '200':
          description: Authentication status
          content:
            application/json:
              schema:
                type: object
                properties:
                  usingDefaultPassword:
                    type: boolean
                  username:
                    type: string

  /api/v1/auth/change-password:
    post:
      summary: Change password
      description: Change the authentication password (requires current password for security)
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currentPassword
                - newPassword
              properties:
                currentPassword:
                  type: string
                  description: Current password for verification
                newPassword:
                  type: string
                  description: New password to set
            example:
              currentPassword: "oldpassword123"
              newPassword: "newpassword456"
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Password changed successfully"
        '400':
          description: Bad request (missing parameters or password validation failed)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "New password does not meet requirements or failed to save"
        '401':
          description: Current password is incorrect
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Current password is incorrect"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Failed to retrieve current password"

  /api/v1/auth/reset-password:
    post:
      summary: Reset password to default
      description: Reset the authentication password to the default value
      tags:
        - Authentication
      responses:
        '200':
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Password reset to default"
        '500':
          description: Failed to reset password
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string

  # OTA (Over-The-Air) Update endpoints
  /api/v1/ota/upload:
    post:
      summary: Upload firmware for OTA update
      description: |
        Upload a new firmware binary for over-the-air update.
        
        **Requirements:**
        - File must be in .bin format
        - Minimum file size: 100KB
        - File must contain valid ESP32 firmware
        - Optional: Include X-MD5 header for verification
      tags:
        - OTA Updates
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                firmware:
                  type: string
                  format: binary
                  description: Firmware binary file (.bin format, minimum 100KB)
      parameters:
        - in: header
          name: X-MD5
          required: false
          schema:
            type: string
            pattern: '^[a-f0-9]{32}$'
          description: Optional MD5 hash of the firmware file for verification
      responses:
        '200':
          description: Firmware uploaded and applied successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Firmware update successful"
        '400':
          description: Bad request (invalid file format, empty file, insufficient size, missing headers, etc.)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    examples:
                      empty_file: 
                        value: "Missing Content-Length header or empty file"
                      too_small:
                        value: "Firmware file too small"
                      wrong_format:
                        value: "File must be in .bin format"
                      insufficient_memory:
                        value: "Insufficient memory for update"
                      no_data:
                        value: "No firmware data received or empty file uploaded"

  /api/v1/ota/status:
    get:
      summary: Get OTA update status
      description: Get information about the current firmware and update status
      tags:
        - OTA Updates
      responses:
        '200':
          description: OTA status information
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "idle"
                  canRollback:
                    type: boolean
                    example: true
                  currentPartition:
                    type: string
                    example: "app0"
                  hasError:
                    type: boolean
                    example: false
                  lastError:
                    type: string
                    example: "No Error"
                  size:
                    type: integer
                    example: 0
                  progress:
                    type: integer
                    example: 0
                  remaining:
                    type: integer
                    example: 0
                  progressPercent:
                    type: integer
                    example: 0
                  currentVersion:
                    type: string
                    example: "00.11.04"
                  currentMD5:
                    type: string
                    example: "ad1783afd0b38f856d5010921712e2ed"

  /api/v1/ota/rollback:
    post:
      summary: Rollback firmware
      description: Rollback to the previous firmware version
      tags:
        - OTA Updates
      responses:
        '200':
          description: Rollback initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Rollback initiated. Device will restart."
        '400':
          description: Rollback not possible
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Rollback not possible"

  # System Management endpoints
  /api/v1/system/info:
    get:
      summary: Get system information
      description: Get detailed system information including firmware, hardware, and build details
      tags:
        - System
      responses:
        '200':
          description: System information
          content:
            application/json:
              schema:
                type: object
                properties:
                  firmware:
                    type: object
                  hardware:
                    type: object
                  build:
                    type: object
                  uptime:
                    type: object

  /api/v1/system/statistics:
    get:
      summary: Get system statistics
      description: Get runtime statistics and performance metrics
      tags:
        - System
      responses:
        '200':
          description: System statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  ade7953TotalInterrupts:
                    type: integer
                  ade7953TotalHandledInterrupts:
                    type: integer
                  mqttMessagesPublished:
                    type: integer
                  wifiConnection:
                    type: integer
                  logCounts:
                    type: object

  /api/v1/system/restart:
    post:
      summary: Restart the system
      description: Initiate a system restart
      tags:
        - System
      responses:
        '200':
          description: Restart initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "System restart initiated"

  /api/v1/system/factory-reset:
    post:
      summary: Factory reset
      description: Reset the system to factory defaults (clears all configuration)
      tags:
        - System
      responses:
        '200':
          description: Factory reset initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Factory reset initiated"

  /api/v1/system/secrets:
    get:
      summary: Check secrets availability
      description: Check if the system has secrets/certificates available
      tags:
        - System
      responses:
        '200':
          description: Secrets status
          content:
            application/json:
              schema:
                type: object
                properties:
                  hasSecrets:
                    type: boolean

  # Network Management endpoints
  /api/v1/network/wifi/reset:
    post:
      summary: Reset WiFi configuration
      description: Reset WiFi settings and restart the WiFi connection
      tags:
        - Network
      responses:
        '200':
          description: WiFi reset initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "WiFi configuration reset"

  /api/v1/network/wifi/info:
    get:
      summary: Get WiFi information
      description: Get current WiFi connection status and network information
      tags:
        - Network
      responses:
        '200':
          description: WiFi information
          content:
            application/json:
              schema:
                type: object
                properties:
                  connected:
                    type: boolean
                  ssid:
                    type: string
                  ipAddress:
                    type: string
                  signalStrength:
                    type: integer
                  macAddress:
                    type: string

  # Logging endpoints
  /api/v1/logs/level:
    get:
      summary: Get current log levels
      description: Get the current print and save log levels
      tags:
        - Logging
      responses:
        '200':
          description: Current log levels
          content:
            application/json:
              schema:
                type: object
                properties:
                  print:
                    type: string
                    enum: [VERBOSE, DEBUG, INFO, WARNING, ERROR, FATAL]
                    example: "INFO"
                  save:
                    type: string
                    enum: [VERBOSE, DEBUG, INFO, WARNING, ERROR, FATAL]
                    example: "WARNING"
    put:
      summary: Set log levels
      description: Update the print and/or save log levels
      tags:
        - Logging
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                print:
                  type: string
                  enum: [VERBOSE, DEBUG, INFO, WARNING, ERROR, FATAL]
                  description: Set the print log level (optional)
                save:
                  type: string
                  enum: [VERBOSE, DEBUG, INFO, WARNING, ERROR, FATAL]  
                  description: Set the save log level (optional)
            example:
              print: "DEBUG"
              save: "ERROR"
      responses:
        '200':
          description: Log levels updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Log levels updated: print=DEBUG save=ERROR"
        '400':
          description: Invalid log level or missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid log level specified. Valid levels: VERBOSE, DEBUG, INFO, WARNING, ERROR, FATAL"

  /api/v1/logs/clear:
    post:
      summary: Clear logs
      description: Clear all stored log entries
      tags:
        - Logging
      responses:
        '200':
          description: Logs cleared successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Logs cleared successfully"

tags:
  - name: System
    description: System management and information endpoints
  - name: Authentication
    description: Authentication and security endpoints
  - name: OTA Updates
    description: Over-the-air firmware update endpoints
  - name: Network
    description: Network and WiFi management endpoints
  - name: Logging
    description: Log management and configuration endpoints

components:
  schemas:
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Operation completed successfully"
    
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "Error message describing what went wrong"
    
    LogLevel:
      type: string
      enum: [VERBOSE, DEBUG, INFO, WARNING, ERROR, FATAL]
      description: Log level enumeration