name: PlatformIO Build

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          ~/.cache/pip
        key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Create dummy secrets
      working-directory: source
      run: |
        mkdir -p secrets
        echo "dummy" > secrets/privateclaim.pem
        echo "dummy" > secrets/certclaim.pem
        echo "dummy" > secrets/ca.pem
        echo "dummy" > secrets/encryptionkey.txt
        echo "dummy" > secrets/endpoint.txt
        echo "dummy" > secrets/rulemeter.txt

    - name: Build firmware (esp32dev)
      working-directory: source
      run: |
        echo "🏗️ Building firmware for esp32dev..."
        pio run -e esp32dev
        echo "✅ Build completed for esp32dev!"

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-esp32dev
        path: source/.pio/build/esp32dev/firmware.bin
        retention-days: 7
